version: '3.8'
name: simplenotes

services:
  db_postgres:
    image: postgres:14.5
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_DB=db_postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5501:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: SimpleNotes/Dockerfile
    container_name: simplenotes_app
    restart: always
    depends_on:
      - db_postgres
    ports:
      - "5002:80"
      - "5003:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Db_Postgres=Host=db_postgres;Port=5432;Database=db_postgres;Username=admin;Password=admin"

volumes:
  pg-data:
    driver: local
