version: '3.8'
name: simplenotes

services:
  wsearch_main:
    image: postgres:14.5
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_DB=db_postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5501:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local